# Generated by Django 4.0.8 on 2023-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Fdate', models.DateField()),
                ('Ffare', models.FloatField()),
                ('Fstart', models.CharField(max_length=20)),
                ('Fend', models.CharField(max_length=20)),
            ],
        ),
    ]
